repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: "output/.*\\.json"
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: '7bcc70ca475b87e0fdee2511300c74b25babe0b3'  # frozen: v0.1.9
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]
