# Left pycharm settings untouched
exclude: .idea/

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: "output/.*\\.json"
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: '343c49ab887fa4e5724ceb86c9c3678e647c94c2'  # frozen: v0.0.262
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: bf7a16254ec96b084a6caf3d435ec18f0f245cc7  # frozen: 23.3.0
  hooks:
  - id: black
    language_version: python3
