"""Constants for use in other files."""

# Cryptic fish families that are recorded on both M1 and M2.
CRYPTIC_FAMILIES = {
    "Agonidae",
    "Ambassidae",
    "Anarhichadidae",
    "Antennariidae",
    "Aploactinidae",
    "Apogonidae",
    "Ariidae",
    "Aulopidae",
    "Bathymasteridae",
    "Batrachoididae",
    "Blenniidae",
    "Bothidae",
    "Bovichtidae",
    "Brachaeluridae",
    "Brachionichthyidae",
    "Bythitidae",
    "Callionymidae",
    "Caracanthidae",
    "Carapidae",
    "Centriscidae",
    "Chaenopsidae",
    "Chironemidae",
    "Cirrhitidae",
    "Clinidae",
    "Congridae",
    "Congrogadidae",
    "Cottidae",
    "Creediidae",
    "Cryptacanthodidae",
    "Cyclopteridae",
    "Cynoglossidae",
    "Dasyatidae",
    "Diodontidae",
    "Eleotridae",
    "Gnathanacanthidae",
    "Gobiesocidae",
    "Gobiidae",
    "Grammistidae",
    "Hemiscylliidae",
    "Heterodontidae",
    "Holocentridae",
    "Hypnidae",
    "Labrisomidae",
    "Leptoscopidae",
    "Liparidae",
    "Lotidae",
    "Monocentridae",
    "Moridae",
    "Muraenidae",
    "Nototheniidae",
    "Ophichthidae",
    "Ophidiidae",
    "Opistognathidae",
    "Orectolobidae",
    "Paralichthyidae",
    "Parascylliidae",
    "Pataecidae",
    "Pegasidae",
    "Pempheridae",
    "Pempherididae",
    "Pholidae",
    "Pinguipedidae",
    "Platycephalidae",
    "Plesiopidae",
    "Pleuronectidae",
    "Plotosidae",
    "Priacanthidae",
    "Pseudochromidae",
    "Psychrolutidae",
    "Rajidae",
    "Rhinobatidae",
    "Scorpaenidae",
    "Serranidae",
    "Scyliorhinidae",
    "Soleidae",
    "Solenostomidae",
    "Stichaeidae",
    "Synanceiidae",
    "Syngnathidae",
    "Synodontidae",
    "Tetrabrachiidae",
    "Tetrarogidae",
    "Torpedinidae",
    "Trachichthyidae",
    "Tripterygiidae",
    "Uranoscopidae",
    "Urolophidae",
    "Zaproridae",
    "Zoarcidae",
}

# Fish genera that are excluded from M2 despite being part of families specified in
# _CRYPTIC_FAMILIES.
M2_GENERA_EXCLUSIONS = {
    "Trachinops",
    "Caesioperca",
    "Lepidoperca",
    "Odontanthias",
    "Plectranthias",
    "Pseudanthias",
    "Selenanthias",
}

# Invertebrate classes that are recorded on M1 (cephalopods and large swimming jellies).
M1_INVERT_CLASSES = {
    "Cubozoa",
    "Cephalopoda",
    "Scyphozoa",
}


# Site names that are corrupted in AODN data, mapped to the correct name.
# This can be removed once the data is fixed.
CORRUPTED_SITE_NAME_CORRECTIONS = {
    "Cala del Pe��on": "Cala del Peñon",
    "El d��ez": "El díez",
    "El Rinc��n": "El Rincón",
    "La R��bita": "La Rábita",
    "Ba��os de Guarda Viejas II": "Baños de Guarda Viejas II",
    "Zacat��n": "Zacatín",
    "La caleta de Salobre��a": "La caleta de Salobreña",
    "Isla de Albor��n (Reserva integral I)": "Isla de Alborán (Reserva integral I)",
    "Isla San Andr��s (Parque Natural)": "Isla San Andrés (Parque Natural)",
    "Coa��a": "Coaña",
    "Puertito de G����mar": "Puertito de Güímar",
    "Espig��n G��imar": "Espigón Güimar",
    "Puerto Col��n Nat": "Puerto Colón Nat",
    "Playa Para��so": "Playa Paraíso",
    "Arme��ime": "Armeñime",
    "Fa��ab��": "Fañabé",
    "MOG��N": "MOGÁN",
    "MONTA��A CLARA": "MONTAÑA CLARA",
    "Llan��a nort": "Llança nort",
    "Bah��a Reix (Parque Natural)": "Bahía Reix (Parque Natural)",
    "El Montgr�� (Parque natural)": "El Montgrí (Parque natural)",
    "El Montgr�� I (Parque natural)": "El Montgrí I (Parque natural)",
    "Jardin bot��nico": "Jardin botánico",
    "Cala Llevad�� (observatorio)": "Cala Llevadó (observatorio)",
    "Benz��": "Benzú",
    "Bah��a Oeste Puerto Williams": "Bahía Oeste Puerto Williams",
    "Bah��a San Telmo Sth": "Bahía San Telmo Sth",
    "Bah��a Guacamaya  Costa Rica": "Bahía Guacamaya  Costa Rica",
    "Bah��a Western (s) Cocos": "Bahía Western (s) Cocos",
    "Bah��a Damas Sur": "Bahía Damas Sur",
    "Bah��a Darwin Pared Este": "Bahía Darwin Pared Este",
    "Bah��a Darwin Pared Norte": "Bahía Darwin Pared Norte",
    "Bah��a Gardner Norte (1)": "Bahía Gardner Norte (1)",
    "Bah��a Gardner Norte (2)": "Bahía Gardner Norte (2)",
    "Bah��a Gardner Sur": "Bahía Gardner Sur",
    "Bah��a Raya, Isla de la Plata": "Bahía Raya, Isla de la Plata",
    "Bah��a Sullivan": "Bahía Sullivan",
    "Bartolom��": "Bartolomé",
    "Genovesa Protecci��n Este": "Genovesa Protección Este",
    "Genovesa Protecci��n Oeste": "Genovesa Protección Oeste",
    "Los Ca��ones Pesca (1)": "Los Cañones Pesca (1)",
    "Los Ca��ones Pesca (2)": "Los Cañones Pesca (2)",
    "Para��so de Pedro": "Paraíso de Pedro",
    "Punta Cormor��n": "Punta Cormorán",
    "Punta Luz de D��a": "Punta Luz de Día",
    "Punta Luz de D��a Oeste": "Punta Luz de Día Oeste",
    "Bah��a Wafer": "Bahía Wafer",
    "Roca Aleta de Tibur��n": "Roca Aleta de Tiburón",
    "Bah��a Iglesias": "Bahía Iglesias",
    "Bah��a Inutil": "Bahía Inutil",
    "Bah��a Carrillo 1": "Bahía Carrillo 1",
    "Bah��a Carrillo 2 (NW)": "Bahía Carrillo 2 (NW)",
    "Bah��a Carrillo 3 (N)": "Bahía Carrillo 3 (N)",
    "Bah��a Carrillo 4": "Bahía Carrillo 4",
    "Bah��a Islita": "Bahía Islita",
    "Bah��a Camaronal": "Bahía Camaronal",
    "Punta San Jos��": "Punta San José",
    "Bola��os Isla": "Bolaños Isla",
    "Jicar��n Noroeste": "Jicarón Noroeste",
    "Ald��n. Praia do Portal": "Aldán. Praia do Portal",
    "Sam��na": "Saména",
    "Aguad��": "Aguadú",
    "Cabo Ti��oso": "Cabo Tiñoso",
    "Pe��a Rota Norte": "Peña Rota Norte",
    "EL PE��ONCITO": "EL PEÑONCITO",
    "Pe��a Rota Sur": "Peña Rota Sur",
    "G��sodden": "Gåsodden",
    "Bouddi ��� Maitland Bay": "Bouddi – Maitland Bay",
    "Bouddi ��� Caves Bay": "Bouddi – Caves Bay",
    "Castell��n II": "Castellón II",
}
