name: Lint checks & tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # pin@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b  # pin@v4.6.0
        with:
          python-version: "3.10"

      - name: Set up cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8  # pin@v3.3.1
        id: cache
        with:
          path: |
            .venv
            ~/.poetry
            ~/.cache
          key: venv-${{ hashFiles('poetry.lock', '.pre-commit-config.yaml') }}

      - name: Install poetry
        run: pipx install poetry==1.4.2

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Run mypy
        run: |
          poetry run mypy \
            --ignore-missing-imports \
            --check-untyped-defs \
            --disallow-incomplete-defs \
            --show-error-codes \
            --strict \
            rls/ \
            tests/

      - name: Run tests
        run: poetry run pytest
