name: Pre-commit checks & tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .venv
            ~/.poetry
            ~/.cache
          key: venv-${{ hashFiles('poetry.lock', '.pre-commit-config.yaml') }}

      - name: Install poetry
        run: |
          curl -sSL \
            "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python

      - name: Install dependencies
        run: |
          source "$HOME/.poetry/env"
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run pre-commit
        run: |
          source "$HOME/.poetry/env"
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          source "$HOME/.poetry/env"
          poetry run pytest
